# .slather.yml

ci_service: travis_ci
coverage_service: coveralls
xcodeproj: SwiftURLMock.xcodeproj
workspace: SwiftURLMock.xcodeproj/project.xcworkspace
scheme: SwiftURLMock
source_directory: SwiftURLMock/
ignore: 
  - ExamplePodCode/*
  - ProjectTestsGroup/*
